### ISSUE TITLE
font-family not working

### ISSUE THREAD

**Issue by Tahmasb** [dendrofen/react-konva-to-svg#1]
every thing is good but font-family not working in svg. any way to solve this problem?

**Comment by dendrofen** [comment]
@Tahmasb svg is text based, svg elements are using font with css. So, to make your font work, act like with any other page html element, include this font on page.

**Comment by dendrofen** [comment]
@Tahmasb Here is updated demo with custom font
https://dendrofen.github.io/react-konva-to-svg/

**Comment by Tahmasb** [comment]
I don't know where my mistake is because I proceed exactly according to the document, but the code does not work

this is my code 
```
  const handleExport = async () => {
    const svg = await exportStageSVG(stageRef.current, false, {
      onBefore: ([stage, layer]) => {},
      onAfter: ([stage, layer]) => {},
    });
    console.log(svg);
  };
<Stage
        ref={stageRef}
        width={window.innerWidth}
        height={window.innerHeight}
      >
  <Layer>
     <Text
            text={"مجتبی احمدی"}
            fontFamily={"regular"}
            x={100}
            y={200}
            draggable
            fontSize={20}
          />
  </Layer>
</Stage>
  
```
and this is my export svg 

`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="958" height="909"><defs/><g><g><path fill="red" stroke="none" paint-order="stroke fill markers" d=" M 33 100 L 467 100 L 467 100 A 33 33 0 0 1 500 133 L 500 367 L 500 367 A 33 33 0 0 1 467 400 L 33 400 L 33 400 A 33 33 0 0 1 0 367 L 0 133 L 0 133 A 33 33 0 0 1 32.99999999999999 100 Z"/></g><g><g><text fill="black" stroke="none" font-family="regular" font-size="40px" font-style="normal" font-weight="normal" text-decoration="undefined" x="0" y="20" text-anchor="start" dominant-baseline="central" transform="matrix(1 0 0 1 100 200)">مجتبی احمدی</text></g></g></g></svg>`

font-family(regular) exist in svg code but not apply on svg when opened

Can you guide me where my mistake is?

**Comment by dendrofen** [comment]
@Tahmasb Your code is ok. Font Family is rendering with browser, maybe in your browser there is no "regular" font-family, try to use different font-family or use google fonts (or similar) to include fonts on page
https://fonts.google.com/
